services:
  influxdb:
    image: influxdb:2.7.5-alpine
    env_file:
      - influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
  mysql:
    image: mysql:8.3
    container_name: openstef-mysql
    volumes:
      - ./mysql/volumes/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tst_icarus
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    container_name: openstef-phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
  grafana:
    image: grafana/grafana:9.3.4
    container_name: openstef-grafana
    ports:
      - 3000:3000
    environment:
      GF_PANELS_DISABLE_SANITIZE_HTML: "true"
  grafana-configurator:
    image: alpine:3.7
    container_name: openstef-grafana-configurator
    depends_on:
      - "grafana"
    command: ["/opt/grafana-configurator/wait-for", "grafana:3000", "--", "sh", "/opt/grafana-configurator/configurator.sh"]
    volumes:
      - ./grafana-configurator/volumes/config:/opt/grafana-configurator
    environment:
      GRAFANA_USER: admin
      GRAFANA_PASSWORD: admin
  influx-configurator:
    container_name: openstef-influx-configurator
    depends_on:
      - "influxdb"
    build:
      context: ./influxdb-configurator
  nginx:
    image: nginx
    container_name: openstef-nginx
    volumes:
      - ./nginx/volumes/config/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/volumes/data:/usr/share/nginx/html
    ports:
      - "8090:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  mlflow:
    build: ./mlflow
    container_name: mlflow
    depends_on:
      - "mysql"
    volumes:
      - ./nginx/volumes/data:/nginx/volumes/data
    ports:
      - "8099:8099"
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=openstef-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mlflow
volumes:
  influxdbv2: