{
 "title": "Station forecasts",
 "time": { "from": "now-7d", "to": "now+2d" },
 "templating": {
  "list": [
   {
    "name": "Prediction_name",
    "label": "Prediction",
    "query": "SELECT p.name from predictions p where p.active=1"
   },
   {
    "name": "Pid",
    "label": "Pid",
    "query": "SELECT id from predictions where name in ('$Prediction_name')"
   },
   {
    "name": "Sigma",
    "query": "select case $Confidence when 98 then 2 when 66 then 1 when 0 then 0 end as sigma"
   },
   {
    "name": "Systems",
    "query": "SELECT s.sid \nFROM systems s LEFT JOIN predictions_systems ps ON ps.system_id = s.sid LEFT JOIN predictions p on ps.prediction_id = p.id \nWHERE p.id='$Pid'"
   },
   { "name": "Confidence", "label": "Confidence [%]", "query": "0,66,98" },
   {
    "name": "SpecifcTAhead",
    "label": "SpecifcTAhead",
    "query": "from(bucket: \"forecast_latest/autogen\")\r\n|> range(start: v.timeRangeStart)\r\n|> filter(fn: (r) => r._measurement == \"prediction_tAheads\")\r\n|> filter(fn: (r) => r.pid == ${Pid:json})\r\n|> keyValues(keyColumns: [\"tAhead\"])\r\n|> group()\r\n|> keep(columns: [\"tAhead\"])\r\n|> distinct(column: \"tAhead\")"
   },
   {
    "name": "PolarityFactorFlippedSystems",
    "query": "SELECT s.sid \nFROM \n\tsystems AS s INNER JOIN predictions_systems AS ps ON ps.system_id = s.sid \nWHERE (s.polarity * ps.factor) < 0 and ps.prediction_id = $Pid"
   },
   {
    "name": "lon",
    "query": "SELECT max(lon) as lon FROM systems WHERE sid IN ($Systems)"
   },
   {
    "name": "lat",
    "query": "SELECT max(lat) FROM systems WHERE sid IN ($Systems)"
   },
   {
    "name": "cid",
    "query": "SELECT customer_id FROM `customers_predictions` where prediction_id=$Pid group by customer_id "
   }
  ]
 },
 "panels": [
  {
   "title": "Total Load - $Prediction_name (pid: $Pid)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "repeat": "Customer",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"forecast_latest/autogen\")\r\n  |> range(start: now(), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prediction\")\r\n  |> filter(fn: (r) => r.pid == ${Pid:json})\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /quantile_P/ or r[\"_field\"] == \"forecast\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: true)\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "positive_systems = from(bucket: \"realised/autogen\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"power\")\r\n|> filter(fn: (r) => r[\"system\"] =~ /^${Systems:regex}$/ and r[\"system\"] !~ /^${PolarityFactorFlippedSystems:regex}$/)\r\n|> filter(fn: (r) => r._field == \"output\")\r\n|> aggregateWindow(every: 15m, fn: mean, createEmpty: false, timeSrc: \"_stop\")\r\n\r\n// Define helper function for multiplication\r\nmultiplyByX = (x, tables=<-) => tables\r\n    |> map(fn: (r) => ({r with _value: r._value * x}))\r\n\r\nnegative_systems = from(bucket: \"realised/autogen\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"power\")\r\n|> filter(fn: (r) => r[\"system\"] =~ /^${PolarityFactorFlippedSystems:regex}$/)\r\n|> filter(fn: (r) => r._field == \"output\")\r\n|> aggregateWindow(every: 15m, fn: mean, createEmpty: true, timeSrc: \"_stop\")\r\ninverted_negative_systems = negative_systems |> multiplyByX(x: -1.0)  \r\n\r\n// Calculate total\r\ncombined = \r\nunion(tables: [inverted_negative_systems, positive_systems]) \r\n|> drop(columns: [\"system\"]) \r\n|> aggregateWindow(every: 15m, fn: sum, createEmpty: true, timeSrc: \"_start\") \r\n\r\n// Combine and show results\r\nunion(tables: [inverted_negative_systems, positive_systems, combined]) \r\n|> keep(columns: [\"_time\", \"_field\", \"_value\", \"system\"])\r\n",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Last measurement",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "from(bucket: \"realised/autogen\")\r\n|> range(start: v.timeRangeStart)\r\n|> filter(fn: (r) => r._measurement == \"power\")\r\n|> filter(fn: (r) => r.system =~ /^${Systems:regex}$/)\r\n|> filter(fn: (r) => r._field == \"created\") \r\n|> max()\r\n|> group()\r\n",
     "select": [
      [
       { "params": [ "created" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$Systems$/" }
     ]
    }
   ]
  },
  {
   "title": "Location $lat, $lon - $Prediction_name (pid: $Pid)",
   "type": "text",
   "description": "Location of the station, determined by the coordinates of one of the systems.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": {
    "content": "<div class=\"mapouter\">\n  <div class=\"gmap_canvas\">\n    <iframe width=\"600\" height=\"275\" id=\"gmap_canvas\" src=\"https://maps.google.com/maps?q=$lat%20$lon&t=&z=9&ie=UTF8&iwloc=&output=embed\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\"></iframe>\n  </div>\n  <style>\n    .mapouter {\n      position: relative;\n      text-align: right;\n      height: 300px;\n      width: 600px;\n    }\n    .gmap_canvas {\n      overflow: hidden;\n      background: none !important;\n      height: 300px;\n      width: 600px;\n    }\n  </style>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Forecast available till",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 2 },
   "repeat": "Predictions",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "prediction",
     "query": "\r\nfrom(bucket: \"forecast_latest/autogen\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"prediction\")\r\n|> filter(fn: (r) => r[\"pid\"] == ${Pid:json})\r\n|> filter(fn: (r) => r._field == \"created\") \r\n|> filter(fn: (r) => r.type != \"est_demand\" and  r.type != \"est_wind\" and  r.type != \"est_pv\")\r\n",
     "select": [
      [
       { "params": [ "created" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "pid", "operator": "=~", "value": "/^$Pid$/" }
     ]
    }
   ]
  },
  {
   "title": "Last update",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 4 },
   "repeat": "Predictions",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prediction",
     "query": "\r\nfrom(bucket: \"forecast_latest/autogen\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"prediction\")\r\n|> filter(fn: (r) => r[\"pid\"] == ${Pid:json})\r\n|> filter(fn: (r) => r._field == \"created\") \r\n|> filter(fn: (r) => r.type != \"est_demand\" and  r.type != \"est_wind\" and  r.type != \"est_pv\")\r\n|> keep(columns: [\"_value\"])\r\n|> max()\r\n|> yield(name: \"max created\")",
     "select": [
      [
       { "params": [ "created" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "pid", "operator": "=~", "value": "/^$Pid$/" }
     ]
    }
   ]
  },
  {
   "title": "Forecast quality @24h ahead",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prediction",
     "query": "from(bucket: \"forecast_latest/autogen\")\r\n|> range(start: 24h, stop: 26h)\r\n|> filter(fn: (r) => r._measurement == \"prediction\")\r\n|> filter(fn: (r) => r[\"pid\"] == ${Pid:json})\r\n|> filter(fn: (r) => r._field == \"quality\")\r\n|> keep(columns: [\"_value\"])",
     "select": [
      [
       { "params": [ "quality" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "pid", "operator": "=~", "value": "/^$Pid$/" }
     ]
    }
   ]
  },
  {
   "title": "Realised and P50 at all tAheads - $Prediction_name (pid: $Pid)",
   "type": "timeseries",
   "description": "Forecast of P50 at all tAheads",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "positive_systems = from(bucket: \"realised/autogen\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"power\")\r\n|> filter(fn: (r) => r[\"system\"] =~ /^${Systems:regex}$/ and r[\"system\"] !~ /^${PolarityFactorFlippedSystems:regex}$/)\r\n|> filter(fn: (r) => r._field == \"output\")\r\n|> aggregateWindow(every: 15m, fn: mean, createEmpty: true, timeSrc: \"_stop\")\r\n// Define helper function for multiplication\r\nmultiplyByX = (x, tables=<-) => tables\r\n    |> map(fn: (r) => ({r with _value: r._value * x}))\r\nnegative_systems = from(bucket: \"realised/autogen\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"power\")\r\n|> filter(fn: (r) => r[\"system\"] =~ /^${PolarityFactorFlippedSystems:regex}$/)\r\n|> filter(fn: (r) => r._field == \"output\")\r\n|> aggregateWindow(every: 15m, fn: mean, createEmpty: true, timeSrc: \"_stop\")\r\ninverted_negative_systems = negative_systems |> multiplyByX(x: -1.0)  \r\n// Calculate total\r\ncombined = \r\nunion(tables: [inverted_negative_systems, positive_systems]) \r\n|> drop(columns: [\"system\"]) \r\n|> aggregateWindow(every: 15m, fn: sum, createEmpty: true, timeSrc: \"_start\")\r\n// Show results\r\ncombined"
    },
    {
     "query": "from(bucket: \"forecast_latest/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prediction_tAheads\")\r\n  |> filter(fn: (r) => r[\"pid\"] == ${Pid:json})\r\n  |> filter(fn: (r) => r[\"_field\"] == \"quantile_P50\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> keep(columns: [\"_time\", \"_field\",\"_value\",\"tAhead\"])"
    }
   ]
  },
  {
   "title": "EAN (if any)",
   "type": "stat",
   "description": "If the prediction is used for TenneT, an EAN is included. Otherwise (usually) not.",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  ean\nFROM predictions\nWHERE\n  id = $Pid\nORDER BY created"
    }
   ]
  },
  {
   "title": "Feature importance - $Prediction_name (pid: $Pid)",
   "type": "text",
   "description": "Relatieve gewichten van het getrainde model. Het oppervlak geeft de *gain* aan, de kleur de _occurence_",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "repeat": "Predictions",
   "options": {
    "content": "<iframe width=\"100%\" height=\"270\" id=\"gmap_canvas\" src=\"http://localhost:8090/icarus/visuals/trained_models/$Pid/weight_plot.html\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\"></iframe>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "API key (if any)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  api_key\nFROM customersApiKeys\nWHERE\n  cid = $cid"
    }
   ]
  },
  {
   "title": "Split components - $Prediction_name (pid: $Pid)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"forecast_latest/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prediction\")\r\n  |> filter(fn: (r) => r[\"pid\"] == ${Pid:json})\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /forecast/)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Quantiles: Forecast and Realised Specific tAhead - $Prediction_name (pid: $Pid)",
   "type": "timeseries",
   "description": "Forecast and Confidence. Confidences in the past are of $SpecificTAhead",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "repeat": "Predictions",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "positive_systems = from(bucket: \"realised/autogen\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"power\")\r\n|> filter(fn: (r) => r[\"system\"] =~ /^${Systems:regex}$/ and r[\"system\"] !~ /^${PolarityFactorFlippedSystems:regex}$/)\r\n|> filter(fn: (r) => r._field == \"output\")\r\n|> aggregateWindow(every: 15m, fn: mean, createEmpty: true, timeSrc: \"_stop\")\r\n// Define helper function for multiplication\r\nmultiplyByX = (x, tables=<-) => tables\r\n    |> map(fn: (r) => ({r with _value: r._value * x}))\r\nnegative_systems = from(bucket: \"realised/autogen\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"power\")\r\n|> filter(fn: (r) => r[\"system\"] =~ /^${PolarityFactorFlippedSystems:regex}$/)\r\n|> filter(fn: (r) => r._field == \"output\")\r\n|> aggregateWindow(every: 15m, fn: mean, createEmpty: true, timeSrc: \"_stop\")\r\ninverted_negative_systems = negative_systems |> multiplyByX(x: -1.0)  \r\n// Calculate total\r\ncombined = \r\nunion(tables: [inverted_negative_systems, positive_systems]) \r\n|> drop(columns: [\"system\"]) \r\n|> aggregateWindow(every: 15m, fn: sum, createEmpty: true, timeSrc: \"_start\")\r\n// Show results\r\ncombined |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    },
    {
     "query": "from(bucket: \"forecast_latest/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prediction_tAheads\")\r\n  |> filter(fn: (r) => r[\"pid\"] == ${Pid:json})\r\n  |> filter(fn: (r) => r[\"tAhead\"] == ${SpecifcTAhead:json})\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /quantile_P/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Predictor 47 hour - $Prediction_name (pid: $Pid)",
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "options": {
    "content": "<iframe width=\"100%\" height=\"300\" id=\"gmap_canvas\" src=\"http://localhost:8090/trained_models/$Pid/Predictor47.0.html\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\"></iframe>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "StDev: Forecast and Realised Specific tAhead - $Prediction_name (pid: $Pid)",
   "type": "timeseries",
   "description": "Forecast and Confidence. Confidences in the past are of $SpecificTAhead",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "positive_systems = from(bucket: \"realised/autogen\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"power\")\r\n|> filter(fn: (r) => r[\"system\"] =~ /^${Systems:regex}$/ and r[\"system\"] !~ /^${PolarityFactorFlippedSystems:regex}$/)\r\n|> filter(fn: (r) => r._field == \"output\")\r\n|> aggregateWindow(every: 15m, fn: mean, createEmpty: true, timeSrc: \"_stop\")\r\n// Define helper function for multiplication\r\nmultiplyByX = (x, tables=<-) => tables\r\n    |> map(fn: (r) => ({r with _value: r._value * x}))\r\nnegative_systems = from(bucket: \"realised/autogen\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"power\")\r\n|> filter(fn: (r) => r[\"system\"] =~ /^${PolarityFactorFlippedSystems:regex}$/)\r\n|> filter(fn: (r) => r._field == \"output\")\r\n|> aggregateWindow(every: 15m, fn: mean, createEmpty: true, timeSrc: \"_stop\")\r\ninverted_negative_systems = negative_systems |> multiplyByX(x: -1.0)  \r\n// Calculate total\r\ncombined = \r\nunion(tables: [inverted_negative_systems, positive_systems]) \r\n|> drop(columns: [\"system\"]) \r\n|> aggregateWindow(every: 15m, fn: sum, createEmpty: true, timeSrc: \"_start\")\r\n// Show results\r\ncombined |> rename(columns: {\"_field\":\"Realised\"})\r\n"
    },
    {
     "query": "forecast = from(bucket: \"forecast_latest/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prediction_tAheads\")\r\n  |> filter(fn: (r) => r.pid == ${Pid:json})\r\n  |> filter(fn: (r) => r[\"tAhead\"] == \"${SpecifcTAhead}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"forecast\" or r[\"_field\"] == \"stdev\")\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: true)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"forecast\", \"stdev\"]) |> rename(columns: {\"forecast\": \"Forecast\"})\r\n\r\n  forecast"
    }
   ]
  },
  {
   "title": "Predictor 15 min - $Prediction_name (pid: $Pid)",
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "options": {
    "content": "<iframe width=\"100%\" height=\"300\" id=\"gmap_canvas\" src=\"http://localhost:8090/trained_models/$Pid/Predictor0.25.html\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\"></iframe>"
   },
   "targets": [
    {}
   ]
  }
 ]
}