{
 "title": "Stationsprognoses",
 "time": { "from": "now-7d", "to": "now+2d" },
 "templating": {
  "list": [
   {
    "name": "Prediction_name",
    "label": "Prediction",
    "query": "SELECT p.name from predictions p where p.active=1 and model='xgb'"
   },
   {
    "name": "Pid",
    "label": "Pid",
    "query": "SELECT id from predictions where name in ('$Prediction_name')"
   },
   {
    "name": "description",
    "query": "SELECT \"description\" FROM \"prediction\" WHERE (\"pid\" =$Pid) AND time >= now() AND  time <= now()+15m"
   },
   {
    "name": "Sigma",
    "query": "select case $Confidence when 98 then 2 when 66 then 1 when 0 then 0 end as sigma"
   },
   {
    "name": "Systems",
    "query": "select s.sid from systems s left join predictions_systems ps on ps.system_id = s.sid left join  predictions p on ps.prediction_id = p.id where p.id='$Pid'"
   },
   { "name": "Confidence", "label": "Confidence [%]", "query": "0,66,98" },
   {
    "name": "SpecifcTAhead",
    "label": "SpecifcTAhead",
    "query": "SHOW TAG VALUES FROM prediction_tAheads WITH key = tAhead where pid =~/$Pid/"
   },
   {
    "name": "PolarityFlippedSystems",
    "query": "SELECT sid from systems where polarity = -1 and sid in ($Systems)"
   },
   {
    "name": "lon",
    "query": "SELECT max(lon) as lon FROM systems WHERE sid IN ($Systems)"
   },
   {
    "name": "lat",
    "query": "SELECT max(lat) FROM systems WHERE sid IN ($Systems)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Load - $Prediction_name (pid: $Pid)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "repeat": "Customer",
   "yaxes": [
    { "format": "short", "label": "Power [MW]" }
   ],
   "targets": [
    {
     "alias": "$description - prognose",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "description" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prediction",
     "query": "SELECT mean(\"forecast\") FROM \"prediction\" WHERE (\"pid\" =~ /^$Pid$/ AND \"time\" > now() AND \"type\" != 'est_demand' AND \"type\" != 'est_pv' AND \"type\" != 'est_wind' and \"quality\" = 'actual') AND $timeFilter GROUP BY time($__interval), \"description\" fill(null)",
     "select": [
      [
       { "params": [ "forecast" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=~", "value": "/^$Predictions$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now()" }
     ]
    },
    {
     "alias": "Totaal - prognose",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prediction",
     "query": "SELECT SUM(mean_forecast) FROM (SELECT mean(\"forecast\") as mean_forecast FROM \"prediction\" WHERE (\"pid\" =~ /^$Pid$/ AND \"time\" > now()AND \"type\" != 'est_demand' AND \"type\" != 'est_pv' AND \"type\" != 'est_wind' and \"quality\" = 'actual') AND $timeFilter GROUP BY time($__interval)) WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "forecast" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=~", "value": "/^$DetailSys$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now()" }
     ]
    },
    {
     "alias": "Totaal - realisatie",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT SUM(mean_output) FROM \n    (SELECT mean(\"output\") as mean_output FROM \"power\" WHERE (\"system\" =~ /^($Systems)$/ and \"system\" !~ /^$PolarityFlippedSystems$/) AND $timeFilter GROUP BY time($__interval), \"system\") ,\n    (SELECT mean(\"output\")*-1 as mean_output FROM \"power\" WHERE (\"system\" =~ /^($Systems)$/ and \"system\" =~ /^$PolarityFlippedSystems$/) AND $timeFilter GROUP BY time($__interval), \"system\")\nWHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "output" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$DetailSys$/" }
     ]
    },
    {
     "alias": "$tag_description - prognose (basecase)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "description" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prediction",
     "query": "SELECT mean(\"forecast\") FROM \"prediction\" WHERE (\"pid\" =~ /^$Pid$/ AND \"time\" > now() AND \"type\" != 'est_demand' AND \"type\" != 'est_pv' AND \"type\" != 'est_wind' and \"quality\" != 'actual') AND $timeFilter AND time>now()+2d GROUP BY time($__interval), \"description\" fill(null)",
     "select": [
      [
       { "params": [ "forecast" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=~", "value": "/^$Predictions$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now()" }
     ]
    },
    {
     "alias": "Totaal - prognose (basecase)",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prediction",
     "query": "SELECT SUM(mean_forecast) FROM (SELECT mean(\"forecast\") as mean_forecast FROM \"prediction\" WHERE (\"pid\" =~ /^$Pid$/ AND \"time\" > now()AND \"type\" != 'est_demand' AND \"type\" != 'est_pv' AND \"type\" != 'est_wind' and \"quality\" != 'actual') AND $timeFilter GROUP BY time($__interval), description) WHERE $timeFilter AND time>now()+2d GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "forecast" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=~", "value": "/^$DetailSys$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now()" }
     ]
    },
    {
     "alias": "$tag_system*-1 - realisatie",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"output\")*-1 FROM \"power\" WHERE (\"system\" =~ /^($Systems)$/ and \"system\" =~ /^$PolarityFlippedSystems$/) AND $timeFilter GROUP BY time($__interval), \"system\" fill(null)",
     "select": [
      [
       { "params": [ "output" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$DetailSys$/" }
     ]
    },
    {
     "alias": "$tag_system - realisatie",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"output\") FROM \"power\" WHERE (\"system\" =~ /^($Systems)$/ and \"system\" !~ /^$PolarityFlippedSystems$/) AND $timeFilter GROUP BY time($__interval), \"system\" fill(null)",
     "select": [
      [
       { "params": [ "output" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$DetailSys$/" }
     ]
    }
   ]
  },
  {
   "title": "Last measurement",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "created" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$Systems$/" }
     ]
    }
   ]
  },
  {
   "title": "Location $lat, $lon - $Prediction_name (pid: $Pid)",
   "type": "text",
   "description": "Location of the station, determined by the coordinates of one of the systems.\n",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": {
    "content": "<div class=\"mapouter\">\n  <div class=\"gmap_canvas\">\n    <iframe width=\"600\" height=\"275\" id=\"gmap_canvas\" src=\"https://maps.google.com/maps?q=$lat%20$lon&t=&z=9&ie=UTF8&iwloc=&output=embed\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\"></iframe>\n  </div>\n  <style>\n    .mapouter {\n      position: relative;\n      text-align: right;\n      height: 300px;\n      width: 600px;\n      \n    }\n    .gmap_canvas {\n      overflow:hidden;\n      background: none!important;\n      height: 300px;\n      width: 600px;\n      \n    }\n  </style>\n</div>"
   }
  },
  {
   "title": "Prediction available till",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 2 },
   "repeat": "Predictions",
   "format": "dateTimeFromNow",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "prediction",
     "select": [
      [
       { "params": [ "created" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "pid", "operator": "=~", "value": "/^$Pid$/" }
     ]
    }
   ]
  },
  {
   "title": "Last update",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 4 },
   "repeat": "Predictions",
   "format": "dateTimeFromNow",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prediction",
     "select": [
      [
       { "params": [ "created" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "pid", "operator": "=~", "value": "/^$Pid$/" }
     ]
    }
   ]
  },
  {
   "title": "Prediction available till",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 6 },
   "format": "dateTimeFromNow",
   "valueName": "last_time",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prediction",
     "select": [
      [
       { "params": [ "forecast" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pid", "operator": "=~", "value": "/^$Pid$/" }
     ]
    }
   ]
  },
  {
   "title": "Forecast and Realised - $Prediction_name (pid: $Pid)",
   "type": "graph",
   "description": "Forecast and Confidence. Confidences in the past are of $SpecifcTAhead",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "repeat": "Predictions",
   "yaxes": [
    { "format": "short", "label": "Power [MW]" }
   ],
   "targets": [
    {
     "alias": "Realised - Total",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT SUM(mean_output) FROM \n    (SELECT mean(\"output\") as mean_output FROM \"power\" WHERE (\"system\" =~ /^$Systems$/ and \"system\" !~ /^$PolarityFlippedSystems$/ ) AND $timeFilter GROUP BY time($__interval), \"system\") ,\n    (SELECT mean(\"output\")*-1 as mean_output FROM \"power\" WHERE (\"system\" =~ /^$Systems$/ and \"system\" =~ /^$PolarityFlippedSystems$/) AND $timeFilter GROUP BY time($__interval), \"system\")\nWHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "output" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "time", "operator": "<", "value": "now()" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$DetailSys$/" },
      { "condition": "AND", "key": "system", "operator": "<>", "value": "Wls-RS_V104" }
     ]
    },
    {
     "alias": "$tag_tAhead Hours Ahead",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"forecast\") FROM \"prediction_tAheads\" WHERE (\"pid\" =~ /^$Pid$/ AND \"type\" != 'est_demand' AND \"type\" != 'est_pv' AND \"type\" != 'est_wind') AND $timeFilter GROUP BY time($__interval), \"tAhead\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"forecast\") + $Sigma * mean(\"stdev\") AS \"Confidence\", mean(\"forecast\") - $Sigma * mean(\"stdev\") AS \"Lower bound\", mean(\"forecast\") as \"Latest Forecast\" FROM \"prediction\" WHERE (\"pid\" =~ /^$Pid$/ AND time > now() AND \"type\" != 'est_demand' AND \"type\" != 'est_pv' AND \"type\" != 'est_wind' AND $timeFilter) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"forecast\")+ $Sigma * mean(\"stdev\") as \"Confidence_hist\", mean(\"forecast\") -  $Sigma * mean(\"stdev\") as \"Lowerbound_hist\" FROM \"prediction_tAheads\" WHERE (\"pid\" =~ /^$Pid$/ AND \"type\" != 'est_demand' AND \"type\" != 'est_pv' AND \"type\" != 'est_wind' ) AND $timeFilter AND time < NOW() AND \"tAhead\" =~ /^$SpecifcTAhead$/ GROUP BY time($__interval), \"tAhead\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Forecast quality",
   "type": "singlestat",
   "description": "Actual - all data for an accurate forecast is present\nCalculated - not all input data was available; a conservative forecast is delivered\nNot_renewed - A major exception occured; the forecast is based on the load of one week earlier",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "prediction",
     "select": [
      [
       { "params": [ "quality" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "pid", "operator": "=~", "value": "/^$Pid$/" },
      { "condition": "AND", "key": "type", "operator": "!~", "value": "/est_*/" }
     ]
    }
   ]
  },
  {
   "title": "Feature importance - $Prediction_name (pid: $Pid)",
   "type": "text",
   "description": "Relatieve gewichten van het getrainde model. Het oppervlak geeft de *gain* aan, de kleur de _occurence_",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "repeat": "Predictions",
   "options": {
    "content": "<iframe width=\"100%\" height=\"270\" id=\"gmap_canvas\" src=\"https://dashboard.icarus.energy/trained_models/$Pid/weight_plot.html\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\"></iframe>"
   }
  },
  {
   "title": "EAN (if any)",
   "type": "singlestat",
   "description": "If the prediction is used for TenneT, an EAN is included. Otherwise (usually) not.",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 10 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  ean\nFROM predictions\nWHERE\n  id = $Pid\nORDER BY created"
    }
   ]
  },
  {
   "title": "API key (if any)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 12 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  apiKey\nFROM customersApiKeys\nWHERE\n  name = '$Prediction_name'\nORDER BY apiKey"
    }
   ]
  },
  {
   "title": "Predictor 15 min - $Prediction_name (pid: $Pid)",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": {
    "content": "<iframe width=\"100%\" height=\"300\" id=\"gmap_canvas\" src=\"https://dashboard.icarus.energy/trained_models/$Pid/Predictor0.25.html\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\"></iframe>"
   }
  },
  {
   "title": "Predictor 47 hour - $Prediction_name (pid: $Pid)",
   "type": "text",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 16 },
   "options": {
    "content": "<iframe width=\"100%\" height=\"300\" id=\"gmap_canvas\" src=\"https://dashboard.icarus.energy/trained_models/$Pid/Predictor47.0.html\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\"></iframe>"
   }
  },
  {
   "title": "Capacity prognosis (if any) - $Prediction_name (pid: $Pid)",
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "options": {
    "content": "<script>\n$(function() {\n    $.ajax({\n        url: \"https://dashboard.icarus.energy/trained_models/$Pid/capacity/capacity_prognoses.html\",\n        dataType: \"jsonp\",\n        timeout: 5000,\n\n        success: function () {\n            $(\"#iframe-capacity\").attr(\"src\", \"https://dashboard.icarus.energy/trained_models/$Pid/capacity/capacity_prognoses.html\");\n        },\n        error: function (parsedjson) {\n            if(parsedjson.status == \"200\") {\n                $(\"#iframe-capacity\").attr(\"src\", \"https://dashboard.icarus.energy/trained_models/$Pid/capacity/capacity_prognoses.html\");\n            } else {\n                $(\"#iframe-capacity\").attr(\"src\", \"https://dashboard.icarus.energy/favicon.ico\");\n            }\n        }\n    });\n});\n</script>\n<iframe width=\"100%\" height=\"300\" id=\"iframe-capacity\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\"></iframe>"
   }
  },
  {
   "title": "Hyperparams - $Prediction_name (pid: $Pid)",
   "type": "table-old",
   "description": "Hyper parameters for the given prediction.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 24 },
   "repeat": "Predictions",
   "targets": [
    {
     "rawSql": "SELECT \n  hpv.created,\n  names.name, \n  hpv.value\nFROM hyper_param_values hpv \nINNER JOIN hyper_params names ON names.id = hpv.hyper_params_id \nINNER JOIN predictions p ON p.id = hpv.prediction_id\nWHERE p.id in ($Pid) AND hpv.created = (SELECT max(created) FROM hyper_param_values WHERE prediction_id = ($Pid))"
    }
   ]
  },
  {
   "title": "Energy split coefficients - $Prediction_name (pid: $Pid)",
   "type": "table-old",
   "description": "Overview of the energy split coefficients for the given prediction.",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  created,\n  coef_name,\n  coef_value\nFROM energy_split_coefs\nWHERE\n  pid = $Pid AND created = (SELECT max(created) from energy_split_coefs WHERE pid =$Pid) ORDER BY coef_name DESC"
    }
   ]
  },
  {
   "title": "Split components - $Prediction_name (pid: $Pid)",
   "type": "graph",
   "description": "Split components for the given prediction. The forecast is the sum of all components.",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Power [MW]" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prediction",
     "select": [
      [
       { "params": [ "forecast" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "forecast (net)" ], "type": "alias" }
      ],
      [
       { "params": [ "forecast_solar" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "pv" ], "type": "alias" }
      ],
      [
       { "params": [ "forecast_wind_on_shore" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "wind_on_shore" ], "type": "alias" }
      ],
      [
       { "params": [ "forecast_other" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "other" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer", "operator": "=~", "value": "/^$Prediction_name$/" },
      { "condition": "AND", "key": "pid", "operator": "=~", "value": "/^$Pid$/" }
     ]
    }
   ]
  },
  {
   "title": "Flatliners (if any) - $Prediction_name (pid: $Pid)",
   "type": "text",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 24 },
   "options": {
    "content": "<script>\r\n$(function() {\r\n    $.ajax({\r\n        url: \"https://dashboard.icarus.energy/trained_models/$Pid/stations_detection.html\",\r\n        dataType: \"jsonp\",\r\n        timeout: 5000,\r\n\r\n        success: function () {\r\n            $(\"#iframe\").attr(\"src\", \"https://dashboard.icarus.energy/trained_models/$Pid/stations_detection.html\");\r\n        },\r\n        error: function (parsedjson) {\r\n            if(parsedjson.status == \"200\") {\r\n                $(\"#iframe\").attr(\"src\", \"https://dashboard.icarus.energy/trained_models/$Pid/stations_detection.html\");\r\n            } else {\r\n                $(\"#iframe\").attr(\"src\", \"https://dashboard.icarus.energy/favicon.ico\");\r\n            }\r\n        }\r\n    });\r\n});\r\n</script>\r\n<iframe width=\"100%\" height=\"300\" id=\"iframe\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\"></iframe>"
   }
  }
 ]
}